# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('start_time',)},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='create_time',
            new_name='start_time',
        ),
        migrations.AlterField(
            model_name='task',
            name='dep_graph',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='jtree_strct',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
