# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0002_auto_20160622_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
