# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0003_auto_20160622_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('dp_id', models.AutoField(primary_key=True, serialize=False)),
                ('privacy_level', models.PositiveSmallIntegerField(default=0)),
                ('epislon', models.FloatField(default=0.0)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('synthetic_path', models.CharField(max_length=300)),
                ('statistics_err', models.TextField(blank=True)),
                ('log_path', models.CharField(blank=True, max_length=300)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desktop.Task')),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
    ]
