# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0005_auto_20160622_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='epislon',
            field=models.FloatField(),
        ),
    ]
