# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0006_auto_20160622_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='epislon',
            new_name='epsilon',
        ),
    ]
